### PR TITLE
Fix boot rom types

### PR DESCRIPTION
**Pull request by greyrogue**
- boot0.rom is for the official FDS BIOS.  It can exist alone or with boot1.rom or boot2.rom.  It wil auto load, but won't auto start unless boot2.rom exists.  It will be in place for any FDS images loaded later
- boot1.rom is for any NES cartridge.  It can be used with boot0.rom.  The boot1.rom will load and start on core start.
- boot2.rom is for any FDS image.  It requires boot0.rom in place.  The FDS image will auto load and start on core start.
- boot3.rom is for the official FDS BIOS and replaces boot0.rom.  It should be used alone. It will auto load and start on core start, and will be in place for any FDS images loaded later.

### CODE REVIEW

**Comment by sorgelig** [comment]
How about let the boot0.rom autostart if no boot1.rom present?
In this case boot3.rom won't be required

**Comment by sorgelig** [comment]
I think it can be prioritized:
- boot0 + boot1 + boot2  - then start boot2. boot1 effectively will be overwritten by boot2 and discarded. 
- boot0 + boot1 - then start the boot1
- boot0 - start the boot0.

**Comment by greyrogue** [comment]
I suggested the same, but people actually requested a black screen option, so I separated the boot0 from boot3 so it's optional. It doesn't hurt anything to have the option of a black screen, even if I don't see the appeal.

**Comment by James-F2** [comment]
Yes, many people like black screen including myself.
It was starting to get annoying to see the FDS bios all the time at core boot.

**Pull request merged**
