### PR TITLE
OSD Optimizations

### PR DESCRIPTION
**Pull request by birdybro**
* Moved FDS Auto Swap and Pause when OSD Open toggles to new Miscellaneous submenu. These options are often not changed by the user.
* Put Savestates into their own subfolder as users typically have easy access to all functions via the savestate hotkey in this core.
* Moved palette options to Audio & Video as the palettes are now very mature and less swapping will probably be needed.
* This new UX design fits on one page of the OSD.

After discussing it a bit with @Kitrinx I think these changes to the OSD will be appropriate and simplify the user experience. I'm open to any suggestions or feedback. :)

### CODE REVIEW

**Comment by thehughhefner** [comment]
I'm not fond of moving save states to its own folder. Please keep it where it belongs

**Comment by sorgelig** [comment]
When you don't use some option/core for a long time, it's hard to remember hotkeys, so it's easier to use OSD directly. So personally i agree that savestates (and saves) must be in the root. Besides to be "nice", the main purpose of OSD is functionality.

**Comment by thehughhefner** [comment]
> When you don't use some option/core for a long time, it's hard to remember hotkeys, so it's easier to use OSD directly. So personally i agree that savestates (and saves) must be in the root. Besides to be "nice", the main purpose of OSD is functionality.

I agree.

So to give feedback to @birdybro, in my opinion, l don't think this is necessary to be done and it will be confusing for the user. Root should have the important stuff and right now in my opinion, root is not cluttered.

**Comment by sorgelig** [comment]
> * Moved FDS Auto Swap and Pause when OSD Open toggles to new Miscellaneous submenu. These options are often not changed by the user.
> * Moved palette options to Audio & Video as the palettes are now very mature and less swapping will probably be needed.

these should be fine IMHO

**Comment by birdybro** [comment]
Thank you for the feedback, I appreciate it! Yeah savestates was one where I wasn't too sure about as well! I'll make the changes!

**Comment by birdybro** [comment]
Done! :)

**Pull request merged**
