### PR TITLE
Fix HQ2X

### PR DESCRIPTION
**Pull request by paulb-nl**

### CODE REVIEW

**Comment by sorgelig** [comment]
Using clock as a signal under other clock domain is really bad idea.

**Comment by sorgelig** [comment]
what issue you have in particular?

**Comment by paulb-nl** [comment]
That is your own code.....
https://github.com/MiSTer-devel/NES_MiSTer/commit/023131d21f66e52e6024756659ec1e26b9c57310#diff-9e8d56e3356eaea2ee789c2918ea3127

It is a partial revert for this issue HQ2x freezes the video. https://github.com/MiSTer-devel/NES_MiSTer/issues/153

**Comment by sorgelig** [comment]
Because of issue to use clock as signal inside the other clock, the code was changed.

**Comment by sorgelig** [comment]
i will fix hq2x mode

**Comment by sorgelig** [comment]
i've fixed it.

**Comment by paulb-nl** [comment]
Thanks!

**Pull request closed without merging**
