### PR TITLE
Updated README to include supported mappers for savestates

### PR DESCRIPTION
**Pull request by retrocaster**

### CODE REVIEW

**Comment by retrocaster** [comment]
It looks like this list needs to be updated if greyrogue's change goes in first: https://github.com/MiSTer-devel/NES_MiSTer/pull/286
I can do that if you want.

**Comment by paulb-nl** [comment]
It would be a lot cleaner if save state support is indicated in the Supported Mappers table.

**Comment by retrocaster** [comment]
> It would be a lot cleaner if save state support is indicated in the Supported Mappers table.

Agreed. I just wasn't sure how to best represent it without cluttering that table too much. Any suggestions? Maybe add an asterisk to each mapper that it implemented? (ie 0*)

**Comment by paulb-nl** [comment]
Currently all supported mappers are in bold but maybe we could change it so only mappers with save state support are in bold. So the Key is changed to: **Supported+Save state**, Supported, ~~Not Supported~~.

**Comment by Thelypody** [comment]
On the topic of mapper table, it should be probably expanded to include NES 2.0 mappers with numbers above 255 as several of them are already supported by the core.

**Comment by SegaSnatcher** [comment]
I also think it would be a good idea to just make the bolded mappers in the table those that support save states.

**Comment by sorgelig** [comment]
ok. Update table with savestate support and i will merge it.

**Pull request merged**
