### PR TITLE
Add an option to Upgrade SNAC Protocol for control a Second Joystick to NES

### PR DESCRIPTION
**Pull request by neurorulez**
To wire the second Joy.
Use same Power pin, GND and Strobe (USER_IO[0]) in Joy 2 like Joy 1
Wire clock pin of joy 2 to USER_IO[[6]
Wire data pin of joy 2 to USER_IO[3]

### CODE REVIEW

**Comment by SegaSnatcher** [comment]
Would this be possible for SNES as well?

**Comment by neurorulez** [comment]
Yes, I have that done in snes too. Later a will make another pr.

**Comment by SegaSnatcher** [comment]
Awesome!!!

**Comment by Kitrinx** [comment]
Actually this isn't right
On SNES there is not enough wires, and on NES, there is also not enough. This will work with controllers but break compatibility with other devices.

**Comment by neurorulez** [comment]
Dont break any compatibility.
In 1 Player mode the core works like now, and in 2 players mode, only 1 IOB and one Data2 Works, like in 1 player mode to work with the other devices.

**Comment by sorgelig** [comment]
I will revert this change.
Kitrinx will work on correct implementation for second controller.

**Comment by neurorulez** [comment]
Ok, i will be waiting to see what is kitrix doing. Some info in advance?. :)

**Comment by Kitrinx** [comment]
I think the right way is to use IO extender chip, with SPI or I2C at a high clock. This will not only take care of level shifting, but allow things like neogeo, multiple controllers, and things like a full famicom expansion port to work, while still being transparently native to the core.

**Pull request merged**
