### PR TITLE
add zapper support via mouse and analog stick

### PR DESCRIPTION
**Pull request by Kitrinx**

### CODE REVIEW

**Comment by sorgelig** [comment]
It seems for games providing the cursor on screen tracking the current position.

**Comment by Kitrinx** [comment]
Right, I draw a little targeting reticule which you can move with either the mouse or analog joystick. There are some modern lightguns that allow you to use mouse movement or joystick movement, so hopefully this will work with those too.

**Comment by sorgelig** [comment]
i see. clever!
I think it's better to rearrange the list of buttons and put trigger before powerpad buttons.

**Comment by Kitrinx** [comment]
I agree, mic too. I could add a "light" button too but I don't think that many of the universal controller adapters would work fast enough for the timing to be right.

**Comment by sorgelig** [comment]
What is "light" button?

**Comment by Kitrinx** [comment]
Zapper has two signals, Trigger (it detects the falling edge, so it goes 0-1-0 when you pull it) and Light, which is active low, which is triggered when the screen goes from dark to light and stays on for about 20 scanlines depending on how bright the light was. Some controller adapters can handle light guns, and do light and trigger buttons out, but I think they're probably too slow to be useful.

**Pull request merged**
