### PR TITLE
Fix mapper 68 mirroring, add battery WRAM support

### LINKED ISSUE #131: Maharaja (FC):  Visual Glitches on boot.
Game has visual glitches on boot and when in game is mainly a black screen with some glitched sprites.

### PR DESCRIPTION
**Pull request by MP2E**
Fixes #131 Maharaja - visual glitches on boot

also tested to make sure saving works and that it is properly backed up to sd card

EDIT: paulb-nl answered my questions and this is now good to merge

### CODE REVIEW

**Comment by paulb-nl** [comment]
You don't need to use prg_bus_write here because that is only used for outputting prg_dout when the address is not in prg_allow. Since prg_dout is always FF it doesn't need to be output to the bus.

Open bus behavior seems to be correct. When ram is disabled for reads at $6000-$7FFF prg_allow is false so reads will be open bus.

**Comment by MP2E** [comment]
Thanks for clearing that up! I have removed the unnecessary changes

**Comment by sorgelig** [comment]
is it final version or there will be fixes?

**Comment by MP2E** [comment]
Yep this is the final version, should be good to merge!

**Pull request merged**
