### PR TITLE
add square pixels aspect ratio option

### PR DESCRIPTION
**Pull request by Chockichoc**
I know it's a sensitive subject so I won't be offended if you refuse my PR.

I believe some nes games have the same problem than some snes games and weren't made with 4:3 aspect ratio in mind. A square pixels option is a good opportunity to correct this problem only for these few games.

In this example (megaman 2), powerups look squished in 4:3. whereas they look prefectly circular in "square pixels" mode :

[4:3](https://i.imgur.com/W8Pycq3.png)
[square pixels](https://i.imgur.com/kPQeyOt.png)

Plus, modern Nintendo games using 8bits graphics often use square pixels. I think it may be a clue that some games were made without taking account that they would be displayed on a 4:3 screen. Square pixels mode could be a way to see what some graphic designers really had in mind when they were designing their games.

For exemple :
[Super Mario 35](https://i.imgur.com/nWn5MAl.png)
[Mario Maker 2](https://i.imgur.com/u2Q3eS4.png)

### CODE REVIEW

**Comment by paulb-nl** [comment]
You forgot to update the Status bit map for the changed menu options.

**Comment by Kitrinx** [comment]
It would be better to add arbitrary aspect ratio support in the ini file rather than clutter the menu with an endless number of niche options like this. 

For the record, games were never "intended" to be seen with square pixels in this era. They were evaluated, playtested, submitted, and released with the CRT aspect ratio present during all of those steps. You may assume that you know better than the people who made the game, or that they were too lazy to fix it, but in the end, this way never a way in which anyone would have ever seen or played this game.

**Comment by Chocobobobo** [comment]
Exact same comment can be made about supporting officially wide ratios as an option to all those old platforms that were never "intended" to be seen as 16:9... #doublestandard #clutteringmenuswithunintendedgarbage

**Comment by Chockichoc** [comment]
> For the record, games were never "intended" to be seen with square pixels in this era

So why circles look squished in the example above, and why a lot of modern games using NES era graphics use square pixels today ? (mario maker etc...)
You may assume that you know better than the people who made the game, but in the end it's just you opinion.
If you don't like square pixels, ok just don't use it. I don't want 4:3 option to be removed, or square pixels to be the default option. I just want to have the opportunity to have the choice between two valid options. (as it is possible with snes core)

**Comment by Chockichoc** [comment]
> 
> 
> You forgot to update the Status bit map for the changed menu options.

Oops ! Thank you for pointing it out to me.

**Comment by SegaSnatcher** [comment]
> Exact same comment can be made about supporting officially wide ratios as an option to all those old platforms that were never "intended" to be seen as 16:9... #doublestandard #clutteringmenuswithunintendedgarbage

Also, even Nintendo themselves offered a square pixel aspect ratio option in their NES and SNES mini consoles.

**Comment by MJY71** [comment]
Adding another aspect ratio option (and one that makes far more sense than the ridiculous 16:9 option) adds no additional clutter to the OSD if the Aspect Ratio menu option is already present and taking up space in the first place. It also adds no more clutter than having a dozen built-in presets for palettes to cycle through (half of which look downright horrible) when the option to load those exact same palettes and many more via the Custom option also exists. It would be nice to remove existing clutter before complaining about additional clutter.

**Comment by SegaSnatcher** [comment]
> Adding another aspect ratio option (and one that makes far more sense than the ridiculous 16:9 option) adds no additional clutter to the OSD if the Aspect Ratio menu option is already present and taking up space in the first place. It also adds no more clutter than having a dozen built-in presets for palettes to cycle through (half of which look downright horrible) when the option to load those exact same palettes and many more via the Custom option also exists. It would be nice to remove existing clutter before complaining about additional clutter.

To be quite honest there really shouldn't be so much restrictions in aspect ratio choice anyways. Ideally the user should be able to choose between many different aspect ratio options, all the way from 16:9 to square pixels and everything in between.  This is possible with the barebones RetroUSB AVS FPGA console. Its not clutter, its just another aspect ratio option that people can take advantage of.  Again, like I said previously. this is an aspect ratio that Nintendo themselves implemented in their NES Classic Mini.  It'd be nice if people coming from the NES Mini who use square pixel option can find that on MiSTer's NES core as well.

**Comment by MJY71** [comment]
Here is a screenshot of the title screen Contra for the NES (with the proposed 'Square Pixels' aspect ratio selected in the OSD) overlaid on top of the title screen of the Contra arcade core. The logos are _now_ an exact match, which tells me all I need to know about "intent".
20201101_091032-screen

**Comment by sorgelig** [comment]
I've introduced custom aspect ratio. Will update NES soon.
So anyone can define his own two aspect ratios either system wide or per core in INI.

**Comment by Chockichoc** [comment]
cool, thanks ♥

**Pull request closed without merging**
